# Generated by Django 2.0.3 on 2018-03-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('id_syrus', models.CharField(max_length=16)),
                ('datatime', models.DateTimeField()),
            ],
        ),
    ]
