# Generated by Django 2.0.3 on 2018-03-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position_data', '0002_auto_20180307_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='position_data',
            name='velocity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position_data',
            name='id_syrus',
            field=models.CharField(default='', max_length=16),
        ),
    ]
